### ISSUE TITLE
Question about tracking of scannumbers

### ISSUE THREAD

**Issue by JannikSchneider12** [PHOENIXcenter/pi-HelixNovo#1]
Hello,

I used the human-epoch-12-step-550000.ckpt to predict sequences from my mgf files. The output file "predictions.txt" contains just the sequences as far as I see. So is it possible to track the input spectra based on the extracted scannumbers or can I map them back via the positional index of the output file?

Thanks for your time and help

**Comment by tingpeng17** [comment]
Thank you for posing the question.
To enhance the usability of pi-HelixNovo, we have uploaded pi-HelixNovo-v1.1. This updated version addresses the requirements you raised.

**Comment by JannikSchneider12** [comment]
Hey , 

Thank your very much for your time and work!
